/**
 * LLM judge for pi-bench.
 *
 * Two backends are supported:
 *   - "api": a model resolved from the pi-ai registry, streamed over HTTP
 *     (e.g. google/gemini-3.1-pro-preview). Works anywhere an API key is available.
 *   - "cli": the `claude` (Claude Code) or `codex` CLI in headless mode. These reuse
 *     whatever login the CLI already has on the machine, so they must run on the HOST,
 *     not inside a SWE-bench container. See scripts/judge-results.ts.
 */

import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

export type JudgeCli = "claude" | "codex";

export const JUDGE_CLIS: JudgeCli[] = ["claude", "codex"];

export interface JudgeVerdict {
  score: number;
  rationale: string;
}

export interface JudgeInput {
  task: any;
  diff: string;
  testExitCode: number | null;
  testOutput: string;
  /** Reference solution diff, if one is known. Falls back to task.expectedDiff. */
  expectedDiff?: string;
  /** True when tests were executed inside an official SWE-bench container. */
  isSweContainer?: boolean;
}

export const JUDGE_SYSTEM_PROMPT = `You are an expert software engineer judging the output of an AI coding agent.
You will be provided with the task prompt, the expected behavior, the git diff generated by the agent, and optionally a known correct "solution diff" and automated test output.
Your job is to determine if the diff successfully accomplishes the task. If automated tests were run, consider them a strong signal, but NOT the absolute ground truth.
If a test fails (e.g., due to strict framework type assertions like expecting an integer instead of a string), but you determine the agent's code practically solves the user's issue in a valid way, you MAY still score it a 1. Provide a detailed rationale explaining why you bypassed the test failure.
Respond ONLY with a JSON object in this exact format, with no markdown wrapping:
{
  "score": 1,
  "rationale": "Explanation for the score"
}`;

/** JSON Schema handed to `codex exec --output-schema` to force the verdict shape. */
const JUDGE_OUTPUT_SCHEMA = {
  type: "object",
  properties: {
    score: { type: "integer", description: "1 if the diff solves the task, 0 otherwise" },
    rationale: { type: "string", description: "Explanation for the score" },
  },
  required: ["score", "rationale"],
  additionalProperties: false,
};

function truncateTestOutput(testOutput: string): string {
  if (testOutput.length <= 15000) return testOutput;
  return (
    testOutput.substring(0, 5000) +
    "\n\n...[TRUNCATED]...\n\n" +
    testOutput.substring(testOutput.length - 10000)
  );
}

export function buildJudgePrompt(input: JudgeInput): string {
  const { task, diff, testExitCode, testOutput, isSweContainer } = input;
  const expectedDiff = input.expectedDiff ?? task.expectedDiff ?? "";

  let testResultsSection = "";
  if (testExitCode !== null && testExitCode !== undefined) {
    const testSource = isSweContainer ? "SWE-bench Container" : "Local";
    const tests = isSweContainer && task.failToPass ? task.failToPass.join(", ") : task.testCommand || "N/A";
    testResultsSection = `Automated Test Execution (${testSource}):\nExit Code: ${testExitCode}\nTests: ${tests}\nOutput:\n${truncateTestOutput(testOutput || "")}\n`;
  }

  return `Task Prompt:
${task.prompt}

Expected Behavior:
${task.expectedBehavior || "Not specified."}

${expectedDiff ? `Known Correct Solution Diff:\n${expectedDiff}\n` : ""}
Agent Diff:
${diff ? diff : "(No changes made)"}

${testResultsSection}
`;
}

export function parseJudgeOutput(raw: string): JudgeVerdict {
  try {
    const jsonStr = raw.match(/\{[\s\S]*\}/)?.[0] || raw;
    const parsed = JSON.parse(jsonStr);
    return { score: Number(parsed.score) || 0, rationale: parsed.rationale ?? "" };
  } catch {
    return { score: 0, rationale: raw || "Failed to parse judge output" };
  }
}

interface SpawnResult {
  stdout: string;
  stderr: string;
  code: number | null;
}

function spawnWithInput(
  command: string,
  args: string[],
  input: string,
  cwd: string,
  timeoutMs: number,
): Promise<SpawnResult> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    let timedOut = false;

    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, timeoutMs);

    child.stdout.on("data", (d) => {
      stdout += d.toString();
    });
    child.stderr.on("data", (d) => {
      stderr += d.toString();
    });
    child.on("error", (err: any) => {
      clearTimeout(timer);
      if (err.code === "ENOENT") {
        reject(
          new Error(
            `Judge CLI '${command}' not found in PATH. Install it and make sure it is logged in, or judge on the host (see README).`,
          ),
        );
      } else {
        reject(err);
      }
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (timedOut) {
        reject(new Error(`Judge CLI '${command}' timed out after ${Math.round(timeoutMs / 1000)}s`));
        return;
      }
      resolve({ stdout, stderr, code });
    });

    child.stdin.end(input);
  });
}

/**
 * Run the judge through a coding-agent CLI in headless mode.
 * Runs in a throwaway cwd so project-level CLAUDE.md / AGENTS.md and settings
 * do not leak into the judge's context.
 */
export async function judgeWithCli(
  cli: JudgeCli,
  prompt: string,
  model?: string,
  timeoutMs: number = 10 * 60 * 1000,
): Promise<string> {
  const scratch = await mkdtemp(join(tmpdir(), "pi-bench-judge-"));
  try {
    if (cli === "claude") {
      const args = [
        "-p",
        "--system-prompt",
        JUDGE_SYSTEM_PROMPT,
        "--output-format",
        "json",
        "--allowed-tools",
        "",
        "--strict-mcp-config",
        "--setting-sources",
        "",
      ];
      if (model) args.push("--model", model);

      const { stdout, stderr, code } = await spawnWithInput("claude", args, prompt, scratch, timeoutMs);
      if (code !== 0) {
        throw new Error(`claude judge exited with code ${code}: ${stderr.trim() || stdout.trim()}`);
      }

      let envelope: any;
      try {
        envelope = JSON.parse(stdout);
      } catch {
        // Not the --output-format json envelope; hand the raw text to the parser.
        return stdout;
      }
      if (envelope.is_error) {
        throw new Error(`claude judge reported an error: ${envelope.result ?? stdout}`);
      }
      return typeof envelope.result === "string" ? envelope.result : JSON.stringify(envelope.result);
    }

    // codex has no system-prompt flag, so the instructions are prepended to the prompt
    // and --output-schema enforces the verdict shape.
    const schemaPath = join(scratch, "judge-schema.json");
    const outPath = join(scratch, "judge-output.json");
    await writeFile(schemaPath, JSON.stringify(JUDGE_OUTPUT_SCHEMA));

    const args = [
      "exec",
      "--skip-git-repo-check",
      "--ephemeral",
      "--sandbox",
      "read-only",
      "--color",
      "never",
      "--output-schema",
      schemaPath,
      "-o",
      outPath,
    ];
    if (model) args.push("-m", model);
    args.push("-");

    const { stdout, stderr, code } = await spawnWithInput(
      "codex",
      args,
      `${JUDGE_SYSTEM_PROMPT}\n\n${prompt}`,
      scratch,
      timeoutMs,
    );
    if (code !== 0) {
      throw new Error(`codex judge exited with code ${code}: ${stderr.trim() || stdout.trim()}`);
    }
    try {
      return await readFile(outPath, "utf-8");
    } catch {
      return stdout;
    }
  } finally {
    await rm(scratch, { recursive: true, force: true });
  }
}

/** Run the judge through a pi-ai registry model over HTTP. */
export async function judgeWithModel(
  judgeModel: any,
  auth: { apiKey?: string; headers?: Record<string, string> },
  prompt: string,
): Promise<string> {
  const { streamSimple } = await import("@mariozechner/pi-ai");
  let judgeOutput = "";
  const stream = streamSimple(
    judgeModel,
    {
      systemPrompt: JUDGE_SYSTEM_PROMPT,
      messages: [{ role: "user", content: prompt, timestamp: Date.now() }],
    },
    { apiKey: auth.apiKey, headers: auth.headers },
  );

  for await (const chunk of stream) {
    if (chunk.type === "text_delta") {
      judgeOutput += chunk.delta;
    }
    if (chunk.type === "error") {
      console.error("[DEBUG] streamSimple error:", chunk.error);
    }
  }
  return judgeOutput;
}
